# Generated by Django 4.2.7 on 2023-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='electric',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='garbage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='water',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='water',
        ),
    ]
