# Generated by Django 4.2.7 on 2023-12-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_complaints_electric_complaints_garbage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(max_length=50, null=True)),
                ('ward_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='council.ward_noo')),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='council.number'),
        ),
    ]
