# Generated by Django 4.2.7 on 2023-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_number_complaints_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='phone_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
