# Generated by Django 4.2.7 on 2023-12-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_alter_number_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(max_length=20, null=True)),
                ('phone_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='council.number')),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='council.date'),
        ),
    ]
