# Generated by Django 4.2.7 on 2023-12-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='members',
        ),
        migrations.CreateModel(
            name='WardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_wards', models.ManyToManyField(to='council.ward_noo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='council.members')),
            ],
        ),
    ]
