# Generated by Django 4.2.7 on 2023-12-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_rename_user_members_wardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='photo',
            field=models.ImageField(null=True, upload_to='complaint_photos/'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='text_area',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
