# Generated by Django 4.2.7 on 2024-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0009_complaints_photo_complaints_text_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
