# Generated by Django 4.2.7 on 2024-01-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0010_complaints_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='is_cancelled',
        ),
    ]
