# Generated by Django 4.2.7 on 2024-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0011_remove_complaints_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
