# Generated by Django 4.2.7 on 2024-01-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0012_members_is_preferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_preferred',
        ),
        migrations.AddField(
            model_name='complaints',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
